"""introduce api server jobs table

Revision ID: 401d3573c0df
Revises: 0ad000429e3d
Create Date: 2023-12-14 13:44:32.708929+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "401d3573c0df"
down_revision = "0ad000429e3d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects_to_api_server_jobs",
        sa.Column("project_uuid", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("solver_key", sa.String(), nullable=True),
        sa.Column("solver_version", sa.String(), nullable=True),
        sa.Column("study_key", sa.String(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_uuid"], ["projects.uuid"], name="project_uuid"
        ),
        sa.ForeignKeyConstraint(
            ["solver_key"], ["services_meta_data.key"], name="Service key for solver"
        ),
        sa.ForeignKeyConstraint(
            ["solver_version"],
            ["services_meta_data.version"],
            name="The version of the solver",
        ),
        sa.ForeignKeyConstraint(
            ["study_key"], ["services_meta_data.key"], name="The key for the study"
        ),
        sa.PrimaryKeyConstraint("job_id"),
        sa.UniqueConstraint("job_id"),
    )
    op.create_index(
        op.f("ix_projects_to_api_server_jobs_project_uuid"),
        "projects_to_api_server_jobs",
        ["project_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_projects_to_api_server_jobs_project_uuid"),
        table_name="projects_to_api_server_jobs",
    )
    op.drop_table("projects_to_api_server_jobs")
    # ### end Alembic commands ###
